"""add jti to auth tokens

Revision ID: 0845e85bec43
Revises: 85f18fd2b8a6
Create Date: 2026-07-10 09:36:32.637091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0845e85bec43'
down_revision: Union[str, Sequence[str], None] = '85f18fd2b8a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_tokens', sa.Column('jti', sa.String(length=36), nullable=True))
    op.alter_column('auth_tokens', 'token_hash',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_unique_constraint(None, 'auth_tokens', ['jti'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_tokens', type_='unique')
    op.alter_column('auth_tokens', 'token_hash',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('auth_tokens', 'jti')
    # ### end Alembic commands ###
