"""allow duplicate user video history

Revision ID: d45abe9da013
Revises: 8106a0033097
Create Date: 2026-07-18 11:06:02.996126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd45abe9da013'
down_revision: Union[str, Sequence[str], None] = '8106a0033097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_video'), 'user_video_history', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_user_video'), 'user_video_history', ['user_id', 'video_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
